### ISSUE TITLE
Tidal Support?

### ISSUE THREAD

**Issue by livewire195** [pendo324/universal-np-extension#11]
Any chance this can be updated for the Tidal Streaming service?  The web player url is https://listen.tidal.com/.

I can provide anything else you need at request.

Thank you for your time!

**Comment by pendo324** [comment]
The next two players I plan on adding are Youtube Music and Tidal. Been a bit busy at my day job so it might take a bit.

**Comment by livewire195** [comment]
Thank you for your effort, I appreciate it!

**Comment by pendo324** [comment]
Closed by #13.

I pushed the updated version of the extension to the Chrome store, and it should be available soon:tm:.

![image](https://user-images.githubusercontent.com/424987/68537569-28b25e80-031b-11ea-98db-5aefe7d4f0f9.png)

Maybe consider rating it ;) (or don't I don't really care).

If you're impatient (like me) you can check out the [releases tab](https://github.com/pendo324/universal-np-extension/releases), download the appropriate zip file, and load the extension manually.

Cheers!
